#from HashTableQuadratic import HashTable

#h = HashTable(5)
#print("Number of items the HashTable", len(h))
#print(h.is_empty())
#print("~"* 20)
#h.put(77,"A")
#h.put(8,"B")
#h.put(1,"C")
#h.put(9,"D")
#print(h)
#h.put(17,"E")
#print("Number of items the HashTable", len(h))
#print(h.is_empty())
#print(h)
#print("#"*20)
#h.remove(8)
#print(h)
#print("@"*20)
#print("Number of items the HashTable", len(h))
#print("+"*20)
#print(f"Value for 77: {h.get(77)}")
#print("+"*20)
#h.put(1,"Z")
#print(h)
#print("^"*20)
#h.put(99,"F")
#h.put(107,"G")
#print(h)
#print("~"*20)
#h.remove(17)
#print(f"Is 99 in table? {h.search(99)}")
#print(h)


